---

mysql_root_password: MYSQL_ROOT_PASSWORD
aegir_db_password: AEGIR_DB_PASSWORD
mariadb_install_from_centos: false
mariadb_my_cnf_configuration: true
aegir_frontend_url: SUBDOMAIN.DOMAIN.TLD
aegir_client_email: ADMIN_EMAIL@DOMAIN.TLD
user_passwordless_sudo: true
#user_authorized_keys: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"