---

mysql_root_password: "MYSQL_ROOT_PASSWORD_ON_AEGIR_SERVER"
mariadb_install_from_centos: true
mariadb_my_cnf_configuration: true
mariadb_galera_configuration: false
user_passwordless_sudo: true
aegir_db_password: "MYSQL_AEGIR_USER_PASSWORD"
aegir_frontend_url: aegir.dev
aegir_client_email: admin@aegir.dev
drupal_console_keep_updated: true
drupal_console_config:
  - vagrant
  - aegir
dotfile_users:
  - {
      name: root,
      dest: /root,
      gitname: GIT_ROOT_NAME,
      gitmail: ROOT@EMAIL
    }
  - {
      name: vagrant,
      dest: /home/vagrant,
      gitname: GIT_VAGRANT_NAME,
      gitmail: VAGRANT@EMAIL
    }
  - {
      name: aegir,
      dest: /var/aegir,
      gitname: GIT_AEGIR_NAME,
      gitmail: AEGIR@EMAIL
    }
