---

- hosts: db
  become: yes
  roles:
    - ansible-role-firewalld
    - ansible-role-mariadb
  vars:
    mariadb_install_from_centos: false
    mysql_root_password: rootdbpassword
    mariadb_my_cnf_configuration: true
    mariadb_galera_configuration: true
    galera_wsrep_cluster_address: gcomm://192.168.33.11,192.168.33.12,192.168.33.13
    galera_wsrep_cluster_name: galera
