---

- hosts: all
  roles:
    - system-initialize
    #- firewall
    - firewalld
    - httpd
    #- php
    #- php55
    - php56
    - composer
    - drush
    - mariadb
    - aegir-user
    - aegir
    - aegir-hosting-queued

  environment:
    PATH: "/usr/local/bin/drush:{{ lookup('env', 'PATH') }}"
