---

- hosts: all
  roles:
    - ansible-role-initialize
    - ansible-role-firewalld
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush
    - mariadb
    - aegir-user
    - aegir
    - aegir-hosting-queued

  environment:
    PATH: "/usr/local/bin/drush:{{ lookup('env', 'PATH') }}"
