---

- hosts: all
  become: yes
  roles:
    - ansible-role-initialize
    - ansible-role-firewalld
    - ansible-role-git
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush
    - ansible-role-mariadb
    - ansible-role-user
    - aegir
    - aegir-hosting-queued
    - dotfiles
  vars:
    aegir_db_password: AEGIR_DB_PASSWORD
    aegir_frontend_url: SUBDOMAIN.DOMAIN.TLD
    aegir_client_email: ADMIN_EMAIL@DOMAIN.TLD
