---

- hosts: all
  become: yes
  roles:
    - ansible-role-initialize
    - ansible-role-firewalld
    - ansible-role-git
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush
    - ansible-role-mariadb
    - ansible-role-user
    - ansible-role-aegir
    - ansible-role-aegir-hosting-queued
    - ansible-role-dotfiles
  vars:
    mysql_root_password: MYSQL_ROOT_PASSWORD
    aegir_db_password: AEGIR_DB_PASSWORD
    aegir_frontend_url: SUBDOMAIN.DOMAIN.TLD
    aegir_client_email: ADMIN_EMAIL@DOMAIN.TLD
    user_passwordless_sudo: true
    dotfile_users:
      root:
        dest: /root
        owner: root
        group: root
        gitname: GIT_ROOT_NAME
        gitmail: ROOT@EMAIL
      aegir:
        dest: /var/aegir
        owner: aegir
        group: aegir
        gitname: GIT_AEGIR_NAME
        gitmail: AEGIR@EMAIL
