---

- hosts: all
  become: yes
  roles:
    - ansible-role-initialize
    - ansible-role-firewalld
    - ansible-role-git
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush
    - ansible-role-mariadb
    - ansible-role-user
    - aegir
    - aegir-hosting-queued
