---

- hosts: all
  become: yes
  roles:
    - ansible-role-initialize
    - ansible-role-yum-repos
    - ansible-role-git
    - ansible-role-dotfiles

- hosts: galera
  become: yes
  roles:
    - ansible-role-firewalld
    - ansible-role-mariadb

- hosts: webserver
  become: yes
  roles:
    - ansible-role-firewalld
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush

- hosts: aegir
  become: yes
  roles:
    - ansible-role-user
    - ansible-role-aegir
    - ansible-role-aegir-hosting-queued

- hosts: fullstack
  become: yes
  roles:
    - ansible-role-firewalld
    - ansible-role-httpd
    - ansible-role-php
    - ansible-role-composer
    - ansible-role-drush
    - ansible-role-mariadb
    - ansible-role-user
    - ansible-role-aegir
    - ansible-role-aegir-hosting-queued
