- name: Clone dot files
  git:
    repo: "{{ dotfile_repo }}"
    dest: "/tmp/dotfiles"
    update: no

- name: Copy dot files
  copy:
    src: /tmp/dotfiles/
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
  with_dict: "{{ dotfile_users }}"

- name: Replace git name
  replace:
    dest: "{{ item.value.dest }}/.gitconfig"
    regexp: "name = *.*"
    replace: "name = {{ item.value.gitname }}"
  with_dict: "{{ dotfile_users }}"

- name: Replace git email
  replace:
    dest: "{{ item.value.dest }}/.gitconfig"
    regexp: "email = *.*"
    replace: "email = {{ item.value.gitmail }}"
  with_dict: "{{ dotfile_users }}"
