
# Define Drush path, usually it's /usr/local/bin
aegir_drush_path: /usr/local/bin

# Default Aegir directory, do not change.
aegir_root: /var/aegir

# Default Aegir user, do not change.
aegir_user: aegir

# Aegir provision version. It should be a stable release.
aegir_provision_version: 7.x-3.6

# Aegir provision version. It should be the same with provision version.
aegir_platform_version: "{{ aegir_provision_version }}"

# Every time we run this script, git will check for source updates.
aegir_provision_update: true

# TODO: replace with tpl file
aegir_makefile_contents: "{{ lookup('file', aegir_makefile) }}"
aegir_makefile: aegir.make

# Aegir front end configuration.
aegir_db_host: localhost
aegir_db_user: aegir
aegir_db_password: aegirdbpassword
aegir_frontend_url: vagrant.dev
aegir_client_email: tovletoglou@gmail.com
