- name: Disable SELinux
  selinux: state=disabled

- name: Update Yum
  yum: name=* state=latest

- name: Install basic packages (git, curl, wget, etc.)
  yum: pkg={{ item }} state=latest
  with_items:
    - git
    - nano
    - curl
    - gcc
    - kernel-devel
    - libzip
    - postfix
    - wget
    - vim
    - man
    - unzip

- name: Install extra packages (nano, tree etc.)
  yum: pkg={{ item }} state=latest
  with_items:
    - nano
    - tree
