allow_url_fopen=On
allow_url_include=Off
date.timezone = Europe/London
display_errors=Off
error_log=/var/log/httpd/php_scripts_error.log
file_uploads=On
log_errors=On
max_execution_time = 60
max_input_time = 60
memory_limit = 256M
post_max_size = 64M
upload_max_filesize = 64M
