- name: Install Webtatic repo
  yum:
    name: "{{ webtatic_repo_url }}"
    state: present

- name: Import Webtatic GPG key
  rpm_key:
    key: "{{ webtatic_repo_gpg_key_url }}"
    state: present

- name: Install php56 from webtatic repository
  yum:
    pkg: "{{ php_modules }}"
    state: "{{ yum_state }}"
    enablerepo: webtatic
  when: ansible_os_family == "RedHat"
  register: webserver_restart_package

- name: Custom php.ini
  template:
    src: custom.php.ini.tpl
    dest: "/etc/php.d/{{ custom_php_ini }}.php.ini"
    owner: root
    group: root
    mode: 0664
  when: create_custom_php_ini
  register: webserver_restart_phpini

- name: Create test phpinfo.php
  template:
    src: phpinfo.php.tpl
    dest: /var/www/html/phpinfo.php
    owner: root
    group: root
    mode: 0664
  when: create_phpinfo

- name: restart webserver
  service:
    name: "{{ webserver }}"
    state: restarted
  when: ( webserver_restart_package.changed or webserver_restart_phpini.changed ) and php_webserver
