# Print firewall rules (true | false)
firewall_debug: false

# Add or remove firewall rules
firewalld_rules:
  ssh:
    port: 22
    protocol: tcp
    state: enabled
    zone: public
    permanent: true
  http:
    port: 80
    protocol: tcp
    state: enabled
    zone: public
    permanent: true
  https:
    port: 443
    protocol: tcp
    state: enabled
    zone: public
    permanent: true
